---
title: "p8105_hw6_yj2687"
author: "Yijia Jiang"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "right"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1 (2017 Central Park Weather Dataset)

```{r, warning=FALSE, message=FALSE}
# Import the dataset
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## Problem 2 (Homicide Dataset)

```{r, warning=FALSE, message=FALSE}
# Import the dataset
homicide_raw <- read_csv(url("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"), na = c("", "NA", "Unknown"))

# Clean dataset
# Create variables city_state, resolved;
# Omit cities without victim race reports and error city;
# Limit victim_race to white or black
homicide_df = homicide_raw %>% 
  janitor::clean_names() %>%
  mutate(reported_date = as.Date(as.character(reported_date), format = "%Y%m%d"),
         victim_age = as.numeric(victim_age),
         city_state = str_c(city, state, sep = ", "),
         resolved = case_when(
           disposition == "Closed without arrest" ~ 0,
           disposition == "Open/No arrest" ~ 0,
           disposition == "Closed by arrest" ~ 1)) %>% 
  relocate(city_state) %>% 
  filter(city_state != c("Dallas, TX","Phoenix, AZ","Kansas City, MO","Tulsa, AL"),
         victim_race == c("White","Black"))
```





## Problem 3 (Child’s birthweight Dataset)

```{r, warning=FALSE, message=FALSE}
# Import the dataset
birthweight_raw <- read_csv("./p8105_hw6_data/birthweight.csv")

# Tidy the dataset
```
